apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: burrow
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burrow
  template:
    metadata:
      labels:
        app: burrow
    spec:
      containers:
      - name: burrow
        image: solsson/burrow@sha256:1f17cb48ba4062b2f796fdf250dce6b6a9d5127b42e15ef2fbc79c68c34ad0ef
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /etc/burrow
      volumes:
      - name: config
        configMap:
          name: burrow-config
