apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: burrow
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burrow
  template:
    metadata:
      labels:
        app: burrow
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: burrow
        image: solsson/burrow@sha256:1f17cb48ba4062b2f796fdf250dce6b6a9d5127b42e15ef2fbc79c68c34ad0ef
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /etc/burrow
      - name: prom
        image: solsson/burrow-exporter:api-v3@sha256:4407616c5720e8a3397f668eec1aaa31df751b3614c0adfc56cae231f2eaeee2
        ports:
        - containerPort: 8080
        env:
        - name: BURROW_ADDR
          value: http://localhost:8000
        - name: METRICS_ADDR
          value: 0.0.0.0:8080
        - name: INTERVAL
          value: "30"
      volumes:
      - name: config
        configMap:
          name: burrow-config
