apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-a
  namespace: kafka
  labels:
    app: mirrormaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirrormaker
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mirrormaker
    spec:
      containers:
      - name: kafka
        image: solsson/kafka:1.1@sha256:ba863ca7dc28563930584e37f93d57c2cbf3f46b1c1fa104fe8af7bcc0c31df4
        command:
        - tail
        - -f
        - /dev/null
